package oj;

/**
 * Created by shiyueqi on 2016/8/29.
 */

import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;

/**
 * Given two strings s and t which consist of only lowercase letters.
   String t is generated by random shuffling string s and then add one more letter at a random position.
   Find the letter that was added in t.

   Example:
   Input:
     s = "abcd"
     t = "abcde"
   Output:
     e

   Explanation:
   'e' is the letter that was added.
 */
public class FindTheDifference_389 {
    public char findTheDifference(String s, String t) {
        char result = 'a';

        Map<Character, Integer> map = new HashMap();

        for (int i = 0; i < t.length(); i++) {
            char tTemp = t.charAt(i);

            if (map.containsKey(tTemp)) {
                map.put(tTemp, map.get(tTemp) + 1);
            } else {
                map.put(tTemp, 1);
            }
        }

        for (int i = 0; i < s.length(); i++) {
            char sTemp = s.charAt(i);

            int value = map.get(sTemp);

            if (value > 1) {
                map.put(sTemp, --value);
            } else {
                map.remove(sTemp);
            }
        }

        Set<Character> set = map.keySet();
        Iterator<Character> it = set.iterator();

        while (it.hasNext()) {
            result = it.next();
        }

        return result;
    }

    public static void main(String[] args) {
        String s = "abcd";
        String t = "abcde";

        char res = new FindTheDifference_389().findTheDifference(s, t);

        System.out.println(res);
    }
}
